In [1]:
#Referensi: https://www.linkedin.com/pulse/how-scrape-google-play-reviews-4-simple-steps-using-python-kundi/

!pip install google-play-scraper

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting google-play-scraper
  Downloading google_play_scraper-1.2.3-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.3

In [2]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [ ]:
# Scrape All available reviews 
#JANGAN DI RUN KODE INI, KECUALI ANDA INGIN SCRAPE SEMUA REVIEWS SEKALIGUS

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'com.bukalapak.android',
    sleep_milliseconds=0, # defaults to 0
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT , you can use Sort.NEWEST to get newst reviews
)

In [3]:
#Scrape desired number of reviews
#Run kode ini jika ingin scrape data dengan jumlah tertentu. Ganti (misal, ingin scrape sejumlah 1000, maka ganti kode , count = 1000 )

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.dafturn.mypertamina',
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=100, # defaults to 100
    filter_score_with=None # defaults to None(means all score) Use 1 or 2 or 3 or 4 or 5 to select certain score
)

In [4]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,f4a31a05-7cbd-41ba-a752-791177cbf47d,31_Nunik Hariadi Putri,https://play-lh.googleusercontent.com/a/AEdFTp...,"Flow aplikasinya tidak jelas, membingungkan pe...",1,130,3.7.4,2023-02-05 02:54:39,None,None
1,2834cf30-e342-4705-a338-efa5d3d6f490,Yus Permadi,https://play-lh.googleusercontent.com/a-/AD5-W...,"Sangat membingungkan, ketika mw manmbahkan dat...",1,9,3.7.5,2023-02-12 01:43:50,None,None
2,44d46e2f-c5c0-482b-87b0-2b32f6d8dcdb,Ahmad Tantowi dastah,https://play-lh.googleusercontent.com/a-/AD5-W...,Kecewa sekaligus membingungkan Setiap mengedit...,1,52,3.7.4,2023-02-09 03:26:35,None,None
3,cbcfeaf8-6a8e-4c6b-8d48-7b74863303cf,DAMAS ANDREAN,https://play-lh.googleusercontent.com/a-/AD5-W...,"Tolong diperbaiki, seharusnya kalo memamang SA...",1,400,3.7.3,2023-01-19 07:44:36,None,None
4,82f61bef-2396-430c-a440-0cb79a6c289c,Easy Live,https://play-lh.googleusercontent.com/a-/AD5-W...,Point perbaikan aplikasi 1. Pop up iklan/info ...,2,480,3.7.3,2022-12-20 01:34:37,None,None

In [5]:
len(df_busu.index) #count the number of data we got

100

In [6]:
df_busu[['userName', 'score','at', 'content']].head()  #preview userName, rating, date-time, and reviews only

,userName,score,at,content
0,31_Nunik Hariadi Putri,1,2023-02-05 02:54:39,"Flow aplikasinya tidak jelas, membingungkan pe..."
1,Yus Permadi,1,2023-02-12 01:43:50,"Sangat membingungkan, ketika mw manmbahkan dat..."
2,Ahmad Tantowi dastah,1,2023-02-09 03:26:35,Kecewa sekaligus membingungkan Setiap mengedit...
3,DAMAS ANDREAN,1,2023-01-19 07:44:36,"Tolong diperbaiki, seharusnya kalo memamang SA..."
4,Easy Live,2,2022-12-20 01:34:37,Point perbaikan aplikasi 1. Pop up iklan/info ...

In [7]:
#Run This Code to Sort the Data By Date 

new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,score,at,content
58,Wawan Suwarman,1,2023-02-12 11:29:51,"Gak jelas, data udah lengkap d foto satu2, pas..."
1,Yus Permadi,1,2023-02-12 01:43:50,"Sangat membingungkan, ketika mw manmbahkan dat..."
7,Zoel Cool,1,2023-02-10 13:09:33,"Ribed,,, susah... Pendaftaran pertama untuk me..."
17,Reki 87,1,2023-02-09 07:26:57,Aplikasi ribet. Tiap login ke data mesti isi p...
2,Ahmad Tantowi dastah,1,2023-02-09 03:26:35,Kecewa sekaligus membingungkan Setiap mengedit...

In [8]:
my_df = sorted_df[['userName', 'score','at', 'content']] #get userName, rating, date-time, and reviews only

In [9]:
my_df.head()

,userName,score,at,content
58,Wawan Suwarman,1,2023-02-12 11:29:51,"Gak jelas, data udah lengkap d foto satu2, pas..."
1,Yus Permadi,1,2023-02-12 01:43:50,"Sangat membingungkan, ketika mw manmbahkan dat..."
7,Zoel Cool,1,2023-02-10 13:09:33,"Ribed,,, susah... Pendaftaran pertama untuk me..."
17,Reki 87,1,2023-02-09 07:26:57,Aplikasi ribet. Tiap login ke data mesti isi p...
2,Ahmad Tantowi dastah,1,2023-02-09 03:26:35,Kecewa sekaligus membingungkan Setiap mengedit...

In [10]:
my_df.to_csv("scrapped_data.csv", index = False)  #Save the file as CSV , to download: click the folder icon on the left. the csv file should be there.